---
# yamllint disable-line rule:line-length
# yaml-language-server: $schema=https://github.com/DavidAnson/markdownlint/raw/main/schema/markdownlint-config-schema.json

# Enable the default rules
default: true

# no-hard-tabs
MD010:
  code_blocks: true
  ignore_code_languages: []
  spaces_per_tab: 2

# line-length
MD013:
  line_length: 80
  heading_line_length: 80
  # Exclude the following elements from
  # maximum line-length checks
  code_blocks: false
  tables: false
  strict: false
  stern: false

# no-inline-html
MD033:
  allowed_elements:
    - a
    - pre
    - br

# no-bare-urls
MD034: false

# table
MD060: false
