---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: 3
output: prefixed
interval: 2s

# Enforce the pipefail option in the Bash library to ensure that where commands
# are run through pipes, the failure of any one step in the pipeline fails the
# whole pipe. For example, terraform |& tee will not normally fail if Terraform
# fails as tee almost always will exit cleanly, unless pipefail is set.
set:
  - pipefail

vars:
  # ANSI Colours
  cr: \e[1;31m
  cg: \e[0;32m
  cw: \e[1;37m
  cc: \e[0m

  # Work out the full path to the root of this repository to allow us to create
  # absolute paths to configuration files, caches, etc., rather than attempt to
  # generate relative links programmatically
  root:
    sh: git rev-parse --show-toplevel

# To help improve management of all the tasks supported within this repository,
# many have been broken out into dedicated files grouped by the sections they
# operate against, so, here, include them into the main Taskfile workflow
includes:
  utils:
    taskfile: .taskfiles/utils.yaml
    flatten: true
  prettier:
    taskfile: .taskfiles/prettier.yaml
    flatten: true
  yamllint:
    taskfile: .taskfiles/yamllint.yaml
    flatten: true
  markdownlint:
    taskfile: .taskfiles/markdownlint.yaml
    flatten: true
  jsonschema:
    taskfile: .taskfiles/jsonschema.yaml
    flatten: true

  development:
    taskfile: .taskfiles/talos.yaml
    dir: development
  production:
    taskfile: .taskfiles/talos.yaml
    dir: production

tasks:
  default:
    desc: Run the development and integration tasks once
    summary: |-
      Clean the environment and then run the development and integration tasks
      for all resources by testing and checking the code and files, but only
      once rather than continuously.

      Use the following command for additional information on the steps
      involved:

      $ task --summary develop
    silent: true
    cmds:
      - task: develop

  develop:
    desc: Continuously run the development and integration tasks
    summary: |-
      The develop task is designed to perform continuous integration on code
      changes within this repository, by running the following tasks when any
      relevant files are changed:

      - Lint all supported files, ensuring their layout and syntax are correct
        and consistent before staging and commiting changes;
    silent: true
    watch: true
    deps:
      - task: pre-commit
      - task: pre-checks
    cmds:
      - task: lint

  lint:
    desc: Lint selected files within this repository
    summary: |-
      Run linting checks across the GitHub Workflows, repository configuration
      files, Terraform (and other) code, and all documentation to find any
      potential issues within the repository by running the following steps:

      - Parse all JSON, YAML, and Markdown files through Prettier in order to
        ensure they are syntactically correct, and that they are consistent in
        their layout and usage;
      - Parse selected configurations (Talos configurations, Task files, GitHub
        Dependabot configuration, and GitHub Workflows) through JSON Schema to
        evaluate these free-from configuration types are correctly structured
        for their intended usage (i.e. keys are in the right place, the values
        are what is expected or supported, and required settings are present);
      - Review the format of Markdown files to ensure they are clean and
        minimise the ability for the page to be incorrectly rendered, such as
        de-duplicating headers, consistent text width, formatted list items,
        and code layouts.
    silent: true
    cmds:
      - task: prettier
      - task: markdownlint
      - task: jsonschema

  clean:
    desc: Clean temporary files from the repository and configurations
    silent: true
    summary: |-
      Clean any temporary directories and files created by both this Taskfile,
      and the tools and applications called from it, and from within the
      configurations.
    run: once
    cmds:
      - cmd: rm -f {development,production}/_build/*.yaml
      - cmd: rm -f .prettiercache
      - cmd: rm -rf .task
      - cmd: echo -e '{{ .cg }}Completed{{ .cc }}'
